In [0]:
#Basic MNIST run

from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 0s 0us/step


In [0]:
train_images.shape

(60000, 28, 28)

In [0]:
test_images.shape, test_labels.shape

((10000, 28, 28), (10000,))

In [0]:
len(train_labels)

60000

In [0]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [0]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
train_images = train_images.reshape((60000, 28*28))

In [0]:
train_images= train_images.astype('float32')/255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32')/255

In [0]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [0]:
network.fit(train_images, train_labels, epochs = 5, batch_size = 128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 4s 70us/step - loss: 0.2590 - acc: 0.9248
Epoch 2/5
60000/60000 [==============================] - 1s 22us/step - loss: 0.1055 - acc: 0.9689
Epoch 3/5
60000/60000 [==============================] - 1s 22us/step - loss: 0.0701 - acc: 0.9796
Epoch 4/5
60000/60000 [==============================] - 1s 22us/step - loss: 0.0510 - acc: 0.9846
Epoch 5/5
60000/60000 [==============================] - 1s 21us/step - loss: 0.0376 - acc: 0.9890


In [0]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 0s 32us/step


In [0]:
print('test_acc:', test_acc)

test_acc: 0.9802


In [0]:
print('test_loss:', test_loss)

test_loss: 0.0708845461825258


In [0]:
#Now we do some basic data rep commands

import numpy as np

In [0]:
x = np.array(12)

In [0]:
x

array(12)

In [0]:
x.ndim

0

In [0]:
x = np.array([12,3,6,14])

In [0]:
x

array([12,  3,  6, 14])

In [0]:
x.ndim

1

In [0]:
print(train_images.ndim)

2


In [0]:
print(test_images.ndim)

2


In [0]:
print(train_labels.ndim)

2


In [0]:
train_images.shape

(60000, 784)

In [0]:
print(train_images.shape)

(60000, 784)


In [0]:
print(x)

[12  3  6 14]


In [0]:
x

array([12,  3,  6, 14])

In [0]:
print(x.ndim)

1


In [0]:
x.ndim

1

In [0]:
#2.3 Implement naive tensor ops

In [0]:
def naive_relu(x):
  assert len(x.shape) == 2
  
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j],0)
  return x

In [0]:
x = np.array([[1],[0]])
y = np.array([[[1],[0]],[[1],[0]]])
z = np.array([[[1,0],[0,0]],[[1,0],[0,0]]])

In [0]:
print ("x = ", x)
print ("y = ", y) 
print ("z = ", z)


x =  [[1]
 [0]]
y =  [[[1]
  [0]]

 [[1]
  [0]]]
z =  [[[1 0]
  [0 0]]

 [[1 0]
  [0 0]]]


In [0]:
type(z[0][0][7])


str

In [0]:
x.ndim

2

In [0]:
x.shape

(2, 1)

In [0]:
naive_relu(x)

array([[1],
       [0]])

In [0]:
# 